/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITest
 * Method:    native_doubleInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNITest_native_1doubleInt
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
